const FALLBACK_VISIBILITY_TIMEOUT = 2000;
const BUDDY_URL = 'https://www.nytimes.com/interactive/2023/upshot/spelling-bee-buddy.html';

const NYT_GAME_WRAPPER_SELECTOR = '#js-hook-game-wrapper';
const NYT_BUDDY_CONTAINER_SELECTOR = '.sb-buddy-container';
const NYT_GRID_SECTION_SELECTOR = '.the-square';
const NYT_TWO_LETTER_LIST_SELECTOR = '.the-square-part-two';

const MIN_SECTION_WIDTH = 300;
const SECTION_GAP = 10;
const IFRAME_HEIGHT_PADDING = 40;
window.SPELLING_BEE_CONSTANTS = {
  FALLBACK_VISIBILITY_TIMEOUT,
  BUDDY_URL,
  NYT_GAME_WRAPPER_SELECTOR,
  NYT_BUDDY_CONTAINER_SELECTOR,
  NYT_GRID_SECTION_SELECTOR,
  NYT_TWO_LETTER_LIST_SELECTOR,
  MIN_SECTION_WIDTH,
  SECTION_GAP,
  IFRAME_HEIGHT_PADDING
};
